name: Awful Poetry
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: Awful Poetry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ded4cc'
    - '#b0a39b'
    - '#9f7f6d'
    - '#533931'
    - '#d83d36'
  brandStrength: 0.8548678702209145
  lightness: 0.3518281646538526
  saturation: 0.5840419849846512
  rhythmicContrast: 0.16042670514434576
purpose: []
